### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mimmi20** [endorphin-studio/browser-detector#20]
```php
[2018-09-17 09:33:17] null.ERROR: Symfony\Component\Yaml\Exception\ParseException: Duplicate key "iCab" detected at line 117 (near "    default: true"). in /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/symfony/yaml/Parser.php:333
Stack trace:
#0 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/symfony/yaml/Parser.php(454): Symfony\Component\Yaml\Parser->doParse(Array, 0)
#1 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/symfony/yaml/Parser.php(315): Symfony\Component\Yaml\Parser->parseBlock(104, 'Epiphany:\n    d...', 0)
#2 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/symfony/yaml/Parser.php(454): Symfony\Component\Yaml\Parser->doParse(Array, 0)
#3 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/symfony/yaml/Parser.php(315): Symfony\Component\Yaml\Parser->parseBlock(43, 'mobile:\n    Dol...', 0)
#4 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/symfony/yaml/Parser.php(95): Symfony\Component\Yaml\Parser->doParse('browser:\n    mo...', 0)
#5 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/symfony/yaml/Parser.php(62): Symfony\Component\Yaml\Parser->parse('###############...', 0)
#6 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/endorphin-studio/browser-detector/src/Storage/YamlStorage.php(34): Symfony\Component\Yaml\Parser->parseFile('/home/developer...')
#7 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/endorphin-studio/browser-detector/src/Detector.php(91): EndorphinStudio\Detector\Storage\YamlStorage->getConfig()
#8 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/scripts/parse.php(35): EndorphinStudio\Detector\Detector->__construct()
#9 {main}
```

**Comment by mimmi20** [comment]
Please check all other yaml files too.

**Comment by serhiime** [comment]
@mimmi20 fixed
