### ISSUE TITLE
creating BrowserDetector fails when located in vendor

### ISSUE THREAD

**Issue by mimmi20** [endorphin-studio/browser-detector#38]
If this project is an dependency of another project, creating a new BrowserDetector instance fails.

```shell
 PHP Fatal error:  Uncaught EndorphinStudio\Detector\Exception\StorageException: /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/endorphin-studio/browser-detector/vendor/endorphin-studio/browser-detector-data/var/yaml is not directory or not exists in /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/endorphin-studio/browser-detector-data/src/Storage/AbstractStorage.php:39
Stack trace:
#0 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/endorphin-studio/browser-detector/src/Detector.php(87): EndorphinStudio\Detector\Storage\AbstractStorage->setDataDirectory('/home/developer...')
#1 /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/scripts/parse-ua.php(25): EndorphinStudio\Detector\Detector->__construct()
#2 {main}
  thrown in /home/developer/projects/useragent-parser-comparison/parsers/endorphin-php-4/vendor/endorphin-studio/browser-detector-data/src/Storage/AbstractStorage.php on line 39
```

**Comment by serhiime** [comment]
@mimmi20 Thanks for your submission. I will try to fix it asap

**Comment by serhiime** [comment]
@mimmi20 Test it please. I think i fixed it at 4.0.3 version

**Comment by mimmi20** [comment]
@serhiime It works now. Thanks

**Comment by serhiime** [comment]
@mimmi20 You are welcome
